[package]
name = "nodejs-tree-sitter-highlight"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]
name = "tree_sitter_highlight"
path = "src/lib.rs"

[dependencies]
highlight-core = { path = "../highlight-core" }
napi.workspace = true
napi-derive.workspace = true
napi-sys.workspace = true
serde_json.workspace = true
tree-sitter.workspace = true

[lints]
workspace = true
