package = "pancat"
version = "0.3.20"
lua = ">=5.1"

[description]
summary = "syntax highlight code in pandoc"
detailed = "A reimplementation of https://github.com/jgm/skylighting by tree-sitter"
maintainer = "Wu"
labels = ["tex"]
homepage = "https://texrocks.readthedocs.io/en/latest/topics/pancat.md.html"
license = "GPL-3.0"

[source]
url = "https://github.com/ustctug/texrocks/archive/$(VERSION).zip"
dir = "texrocks-$(VERSION)/packages/$(PACKAGE)"

[dependencies]
texcat = ">=0.3.20"

[run]
type = "command"
command = "pancat"

[test]
type = "command"
command = "pancat"
flags = ["README.md"]

[build]
type = "builtin"

[deploy]
wrap_bin_scripts = false
