package = "pancat"
version = "0.3.16"
lua = ">=5.1"

[description]
summary = "syntax highlight code in pandoc"
detailed = "A reimplementation of https://github.com/jgm/skylighting by tree-sitter"
maintainer = "Wu"
labels = ["tex"]
homepage = "https://github.com/sphinx-contrib/tree-sitter-highlight"
license = "GPL-3.0"

[source]
url = "https://github.com/sphinx-contrib/tree-sitter-highlight/archive/$(VERSION).zip"
dir = "tree-sitter-highlight-$(VERSION)/packages/lua/$(PACKAGE)"

[dependencies]
texcat = ">=0.3.16"

[run]
type = "command"
command = "pancat"

[test]
type = "command"
command = "pancat"
flags = ["README.md"]

[build]
type = "builtin"

[deploy]
wrap_bin_scripts = false
